world = {
	dialogDone : false,
	e1CommandantLaheartDone : false,
	inquisitionFinished : false,
	// BorderPost
	alazarEdoranOpen : false,
	alazarGosenbergOpen : false,
	gosenbergHaragOpen : false,
	tiltrenHaragOpen : false,
	gosenbergAlazarOpen : false,
	//G1
	g1Captured : false,
	g1BrunhildeDead : false,
	g1BrunhildeAlive : false,
	//Arena
	g1ArenaDone : false,
	g2Arena1Done : false,
	g2Arena2Done : false,
	a1ArenaDone : false,
	h1ArenaDone : false,
	e1ArenaDone : false,
	fishermanChest : false,
	hairGrowingUsed : false,
	championG1Defeated : false,
	tatooAuthorized : false,
	wolfyGiven : false,
	wolfyDead : false,
	wolfyShow : false,
	refugeeGosenbergBorderPostHelped : false,
	stromkappTutoHelp : false,
	//HaragEnd
	h1senunaSaved : false,
	h1trackersEnd : false,
	h1scholarsEnd : false,
	// Rouste
	rousteUnlocked : false,
	//A1
	dragonBonesStart : false,
	dragonBonesCount : 0,
	astronomerLetter : false,
	astronomerLetterDone : false,
	inquisitionSeed : -1,
	indexAlazarInquisition : -1,
 	// Crime Path
	pathCrime1Started : false,
	pathCrime1Accepted : false,
	pathCrime1GuardCounter : 0,
	pathCrime1Ended : false,
	// Might Path
	pathMight1Started : false,
	pathMight1Accepted : false,
	pathMight1DialogIntroDone : false,
	pathMight1Done : false,
	// Trade Path
	pathTrade1Started : false,
	pathTrade1Accepted : false,
	pathTrade1TiltrenAttackers : false,
	pathTrade1TiltrenAttackersKilled : false,
	pathTrade1TiltrenDone : false,
	pathTrade1MarheimDone : false,
	pathTrade1MarheimAttackers : false,
	pathTrade1MarheimAttackersKilled : false,
	pathTrade1MarheimDone : false,
	pathTrade1End : false,
	// Knowledge Path
	pathKnowledge1Started : false,
	pathKnowledge1Accepted : false,
	pathKnowledge1GetMap : false,
	pathKnowledge1End : false,
	pathKnowledge1OnTrack : false,
};